site_name: Comodojo extender documentation
site_favicon: assets/favicon.ico
markdown_extensions:
    - toc:
        permalink: "ïƒ"
    - admonition:
pages:
	- [index.md, Home]
	- [install.md, Installing extender]